### ISSUE TITLE
idock application fault with  ZINC00058183 and others

### ISSUE THREAD

**Issue by tobigithub** [HongjianLi/idock#9]
Hi,
idock 2.1.4 under win
using 1HCL and  ZINC00058183 and ZINC03995861 program crashes (carbon charged I guess)
http://zinc.docking.org/substance/58183

Ligand download from here:
http://zinc.docking.org/pdbqt/drugbank_smallmol/pdbqt/ZINC00058183.pdbqt
http://zinc.docking.org/pdbqt/drugbank_smallmol/pdbqt/ZINC03995861.pdbqt

(I downloaded the tar file from http://zinc.docking.org/pdbqt/)
Tobias

**Comment by HongjianLi** [comment]
Hi,
  The problem lies in the ZINC ligand pdbqt files. At lines 37 and 38, there is an empty branch:
BRANCH  15  23
ENDBRANCH  15  23
  Empty branches provide no information as they contain no atoms. In your case, line 37 is repeated at line 39. Sometimes empty branches are generated by the PDB-to-PDBQT converter prepare_ligand4.py if the input structure is invalid, e.g. when all the atoms are located in the same plane.
  Hence idock v2.1.4 simply throws an exception upon parsing an empty branch. Perhaps in the next release v2.1.5, idock will silently ignore empty branches instead of throwing an exception.

**Comment by HongjianLi** [comment]
Hi Tobias,

Now empty branches are silently ignored in the new release v2.2.0.

**Comment by tobigithub** [comment]
Tnx
